pagopa/idpay-portal-welfare-backend-initiative

src/main/java/it/gov/pagopa/initiative/controller/InitiativeApiController.java
src/main/java/it/gov/pagopa/initiative/service/InitiativeServiceImpl.java
src/test/java/it/gov/pagopa/initiative/controller/InitiativeApiTest.java
src/test/java/it/gov/pagopa/initiative/service/InitiativeServiceTest.java
src/test/java/it/gov/pagopa/initiative/service/InitiativeValidationServiceTest.java

IDP-287 Initiatives filtered by status based on role

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/test/java/it/gov/pagopa/initiative/service/InitiativeServiceTest.java

to cover Beans Context startUp

IDP-384 Added delay field in Test

---

.github/workflows/anchore.yml
Dockerfile
pom.xml

**Description**
The purpose of this PR is to solve the vulnerabilities(CVE) with status high
**List of changes**
- Docker file
- Anchore
- Update dependencies
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**

feat: IDP-1493-risoluzione-cve-idpay-portal-welfare-backend-initiative

---

Dockerfile

fix: IDP-1760 fix new critical CVE-2022-48174 (#173)

---

pom.xml
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeApiRetryable.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/utils/MemoryAppender.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

feat: Release dev

---

Dockerfile
src/main/java/it/gov/pagopa/initiative/dto/BeneficiaryRankingDTO.java
src/main/java/it/gov/pagopa/initiative/dto/RankingRequestDTO.java
src/main/java/it/gov/pagopa/initiative/service/InitiativeServiceImpl.java
src/test/java/it/gov/pagopa/initiative/service/InitiativeServiceTest.java

This PR is related to the task [IDP-1752](https://pagopa.atlassian.net/browse/IDP-1752) about the adjustment of ranking initiative for family unit
- Added `familyId` and `memberIds` in each beneficiaryRanking rows of export ranking file
[IDP-1752]: https://pagopa.atlassian.net/browse/IDP-1752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IDP-1752] added familyUnit to ranking export api

---

src/main/java/it/gov/pagopa/initiative/service/InitiativeServiceImpl.java
src/test/java/it/gov/pagopa/initiative/service/InitiativeServiceTest.java

- Removed condition to check whether an initiative exists upon delete start
- Modified Junit tests

fix: IDP-remove_initiative_exist_check_on_delete

---

src/main/java/it/gov/pagopa/initiative/dto/OnboardingStatusCitizenDTO.java
src/main/java/it/gov/pagopa/initiative/dto/StatusOnboardingDTO.java
src/main/java/it/gov/pagopa/initiative/service/InitiativeServiceImpl.java
src/test/java/it/gov/pagopa/initiative/service/InitiativeServiceTest.java

This PR is related to task [IDP-1823](https://pagopa.atlassian.net/browse/IDP-1823)
- Added familyId in api getOnboardingList
[IDP-1823]: https://pagopa.atlassian.net/browse/IDP-1823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IDP-1823] added familyId in api getOnboardingList

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/main/java/it/gov/pagopa/initiative/dto/QueueCommandOperationDTO.java
src/main/java/it/gov/pagopa/initiative/service/InitiativeServiceImpl.java
src/main/resources/application.yml

The purpose of this pr is to insert two env variables to make the delete configurable.
- Added env variables
- Modified QueueCommandOperationDTO

fix: IDP 1820 paged delete

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/main/java/it/gov/pagopa/initiative/service/InitiativeServiceImpl.java
src/main/resources/application.yml

Removed env values
- Removed env values
- Modified method 

fix: Idp 1820 delete paginata

---

src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/main/java/it/gov/pagopa/common/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java
src/test/java/it/gov/pagopa/common/mongo/DummySpringRepository.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

fix: Idp 2003 fix mongo retry when anonymous repo

---

Dockerfile
pom.xml
src/main/java/it/gov/pagopa/common/stream/StreamsHealthIndicator.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/main/java/it/gov/pagopa/initiative/service/AuditorAwareImpl.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/stream/StreamsHealthIndicatorTest.java

fix: Idp 2016 fix CVE

---

src/main/java/it/gov/pagopa/initiative/utils/AESUtil.java

fix: Sonar Fix

---

src/main/java/it/gov/pagopa/initiative/dto/AutomatedCriteriaDTO.java
src/main/java/it/gov/pagopa/initiative/utils/constraint/initiative/beneficiary/IseeCodeMustHaveValueNumericConstraint.java
src/main/java/it/gov/pagopa/initiative/utils/validator/initiative/beneficiary/IseeCodeMustHaveValueNumericValidator.java
src/test/java/it/gov/pagopa/initiative/controller/InitiativeApiTest.java

fix: Idp 1725 handling invalid ISEE

---

src/main/java/it/gov/pagopa/initiative/dto/AutomatedCriteriaDTO.java
src/main/java/it/gov/pagopa/initiative/utils/AESUtil.java
src/main/java/it/gov/pagopa/initiative/utils/constraint/initiative/beneficiary/IseeCodeMustHaveValueNumericConstraint.java
src/main/java/it/gov/pagopa/initiative/utils/validator/initiative/beneficiary/IseeCodeMustHaveValueNumericValidator.java
src/test/java/it/gov/pagopa/initiative/controller/InitiativeApiTest.java

fix: Sonar Fix (#195)

---

.github/CODEOWNERS
src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java
src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestSyncClient.java
src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java
src/test/java/it/gov/pagopa/initiative/repository/InitiativeRepositoryExtendedImplTest.java
src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports
src/test/resources/mongodbEmbeddedDisabled.properties

chore: IDP-2102 configuring a single mongodb instance for all tests

---

.github/CODEOWNERS
Dockerfile
src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java
src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestSyncClient.java
src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java
src/test/java/it/gov/pagopa/initiative/repository/InitiativeRepositoryExtendedImplTest.java
src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports
src/test/resources/mongodbEmbeddedDisabled.properties

chore: Release dev

---

src/main/java/it/gov/pagopa/initiative/controller/InitiativeApiController.java
src/main/java/it/gov/pagopa/initiative/mapper/InitiativeModelToDTOMapper.java
src/main/java/it/gov/pagopa/initiative/repository/InitiativeRepository.java
src/main/java/it/gov/pagopa/initiative/service/InitiativeServiceImpl.java
src/main/java/it/gov/pagopa/initiative/utils/InitiativeUtils.java
src/test/java/it/gov/pagopa/initiative/controller/InitiativeApiTest.java
src/test/java/it/gov/pagopa/initiative/mapper/InitiativeModelToDTOMapperTest.java
src/test/java/it/gov/pagopa/initiative/service/InitiativeServiceTest.java

- Updated junit
- Added check endDate on mapper method

fix: Idp 2243 added period check for initiative status

---

postman/idpay-initiative-e2e.postman_collection.json

Task [IDP-2129](https://pagopa.atlassian.net/browse/IDP-2129)
- removed real cf from test
[IDP-2129]: https://pagopa.atlassian.net/browse/IDP-2129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [IDP-2129] remove real cf from postman

---

pom.xml

chore: update pom version

---

src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceMetadataDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceRequestDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceRequestMetadataDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceResponseDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceResponseMetadataDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/TopicDTO.java
src/main/java/it/gov/pagopa/initiative/mapper/InitiativeAdditionalDTOsToIOServiceRequestDTOMapper.java
src/test/java/it/gov/pagopa/initiative/connector/io_service/IOManageBackEndFeignRestClientTest.java
src/test/java/it/gov/pagopa/initiative/connector/io_service/IOManageBackEndRestConnectorTest.java
src/test/java/it/gov/pagopa/initiative/mapper/InitiativeAdditionalDTOsToIOServiceRequestDTOMapperTest.java
src/test/java/it/gov/pagopa/initiative/service/InitiativeServiceTest.java

[IDP-2471](https://pagopa.atlassian.net/browse/IDP-2471)
Update connector IO api
[IDP-2471]: https://pagopa.atlassian.net/browse/IDP-2471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IDP-2471] Update connector IO api

---

pom.xml
src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceMetadataDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceRequestDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceRequestMetadataDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceResponseDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceResponseMetadataDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/TopicDTO.java
src/main/java/it/gov/pagopa/initiative/mapper/InitiativeAdditionalDTOsToIOServiceRequestDTOMapper.java
src/test/java/it/gov/pagopa/initiative/connector/io_service/IOManageBackEndFeignRestClientTest.java
src/test/java/it/gov/pagopa/initiative/connector/io_service/IOManageBackEndRestConnectorTest.java
src/test/java/it/gov/pagopa/initiative/mapper/InitiativeAdditionalDTOsToIOServiceRequestDTOMapperTest.java
src/test/java/it/gov/pagopa/initiative/service/InitiativeServiceTest.java

- Update connector IO api -> [PR](https://github.com/pagopa/idpay-portal-welfare-backend-initiative/pull/224)

fix: Promote to UAT

---

pom.xml
src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceMetadataDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceRequestDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceRequestMetadataDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceResponseDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/ServiceResponseMetadataDTO.java
src/main/java/it/gov/pagopa/initiative/dto/io/service/TopicDTO.java
src/main/java/it/gov/pagopa/initiative/mapper/InitiativeAdditionalDTOsToIOServiceRequestDTOMapper.java
src/test/java/it/gov/pagopa/initiative/connector/io_service/IOManageBackEndFeignRestClientTest.java
src/test/java/it/gov/pagopa/initiative/connector/io_service/IOManageBackEndRestConnectorTest.java
src/test/java/it/gov/pagopa/initiative/mapper/InitiativeAdditionalDTOsToIOServiceRequestDTOMapperTest.java
src/test/java/it/gov/pagopa/initiative/service/InitiativeServiceTest.java

- fix connector IO -> [PR](https://github.com/pagopa/idpay-portal-welfare-backend-initiative/pull/224)

fix: Promote to main

---

specs/asyncapi.yml

- Added asyncapi.yml file with async queue census

chore: Idp 2524 censimento async idpay portal welfare backend initiative

---

specs/asyncapi.yml

chore: update asycnapi

---

Dockerfile
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
helm/values.yaml
pom.xml
src/main/java/it/gov/pagopa/initiative/connector/error/decoder/Custom5xxErrorDecoder.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/initiative/config/JsonConfigTest.java
src/test/java/it/gov/pagopa/initiative/config/MongoDBConfigTest.java

- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV, UAT, PROD

chore: fix cve

---

Dockerfile
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
helm/values.yaml
pom.xml
src/main/java/it/gov/pagopa/initiative/connector/error/decoder/Custom5xxErrorDecoder.java
src/test/java/it/gov/pagopa/initiative/config/JsonConfigTest.java
src/test/java/it/gov/pagopa/initiative/config/MongoDBConfigTest.java

- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV, UAT, PROD
[PR](https://github.com/pagopa/idpay-portal-welfare-backend-initiative/pull/234)

chore: promote to UAT

---

Dockerfile
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
helm/values.yaml
pom.xml
specs/asyncapi.yml
src/main/java/it/gov/pagopa/initiative/connector/error/decoder/Custom5xxErrorDecoder.java
src/test/java/it/gov/pagopa/initiative/config/JsonConfigTest.java
src/test/java/it/gov/pagopa/initiative/config/MongoDBConfigTest.java

- Fix CVE [PR](https://github.com/pagopa/idpay-portal-welfare-backend-initiative/pull/235)

chore: promote to MAIN

---

src/main/java/it/gov/pagopa/initiative/mapper/InitiativeModelToDTOMapper.java

fix: null pointer cents

---

src/main/java/it/gov/pagopa/initiative/service/InitiativeValidationServiceImpl.java
src/test/java/it/gov/pagopa/initiative/service/InitiativeValidationServiceTest.java

fix: added check FamilyunitComposition

---

.github/CODEOWNERS
Dockerfile
helm/values-dev.yaml
pom.xml

fix: CVE (#248)

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

chore: helm java_tool_options update

---

Dockerfile
pom.xml

chore: [IDP-2676] jdk update to 21 

---

pom.xml

fix: Idp 2726 risoluzione CVE 2025 21587

---

.devops/code-review-pipelines.yml
Dockerfile
pom.xml
src/test/java/it/gov/pagopa/initiative/controller/InitiativeApiTest.java

chore: [IDP-2676 ]update jdk to 21 

---

pom.xml

chore: [IDP-2676 ]update jdk to 21

---

src/main/java/it/gov/pagopa/initiative/repository/InitiativeRepository.java

Creazione di una nuova API per fornire al FE criteri di valutazione.
Aggiunti i campi privacyLink e tcLink alla chiamata retrieveInitiativeBeneficiaryView

feat: Creating the onboardingWeb API
